### ISSUE TITLE
Input area broken in 2.0.0-pre.6

### ISSUE THREAD

**Issue by MiniDigger** [easymac/lounge-neuron#2]
the input area seems to have changed a bit in the latest versions
![](http://i.minidigger.me/2016/09/chrome_2016-09-04_11-04-57.png)
I crafted a temp fix for myself but I am more of the css hacker type so I will not create a pr for it.
https://www.diffchecker.com/a1dih56c
![](http://i.minidigger.me/2016/09/chrome_2016-09-04_11-08-36.png)

**Comment by easymac** [comment]
Hiya MiniDigger!

Thanks for leaving an issue - never had one left on one of my projects before. Sorry for taking 4 days; I completely forgot about this issue until I noticed it for myself.

I've just pushed a commit to master that fixes all of the CSS issues I've encountered on v2.0.0-pre.5 -- I only upgraded to pre.5 instead of pre.6 because the word on the street is that pre.6 forces you to login all the time.

The CSS appears to be the same, though.

Could you check for me if these changes solved your problem? If not, I'll just upgrade to pre.6 & publish a fix ASAP and just make do until pre.7.

**Comment by MiniDigger** [comment]
Oh, me getting locked out all the time is a bug ^^

Will try the updated can and let you know if it fixed it.

**Comment by MiniDigger** [comment]
I am currently testing it on mobile (chrome on android)  and it looks like the user bar is now broken/transparent ![](https://puu.sh/r3Nzv/5f85cf6e56.png)

**Comment by easymac** [comment]
Ah! Found it & fixed it with a new commit. Grab that one when you get a chance and let me know if you run into any problems / have any suggestions.

**Comment by MiniDigger** [comment]
its not transparent anymore but text doesn't flow around the list anymore. it is reproducable on chrome on my desktop too.
![http://i.minidigger.me/2016/09/2016-09-08_19-28-42.gif](http://i.minidigger.me/2016/09/2016-09-08_19-28-42.gif)
idk if its a bug tho. don't think you want that list open all the time on a small screen. I can't try to repoduce it on a default theme but you should do that before wasting time on trying to fix a bug that does not exist ;)
